[package]
name = "registration_task"
version = "0.1.0"
edition = "2021"

[dependencies]
borsh = "0.10.3"
bs58 = "0.5.1"
solana-client = "1.15.2"
solana-program = "1.15.2"
solana-sdk = "1.15.2"
solana-idlgen = { git = "https://github.com/deanmlittle/solana-idlgen.git" }